version: '2'
services:
    podium-registry:
        container_name: podium-registry
        image: podium/podium-registry:v2.5.5
        volumes:
            - ./central-server-config:/central-config
        # When run with the "dev" Spring profile, the Podium Registry will
        # read the config from the local filesystem (central-server-config directory)
        # When run with the "prod" Spring profile, it will read the config from a git repository
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - SECURITY_USER_PASSWORD=admin
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/localhost-config/
            # - GIT_URI=https://github.com/thehyve/-registry/
            # - GIT_SEARCH_PATHS=central-config
        ports:
            - 8761:8761
